export const sideBarCategory={
        restrant:[
            {
                id:'fastfood',
                name:'fastfood',
                img:'pizza',
                menuNum:1,
                title:'فست فود',
                subCategory:[
                    {
                        id:'pizza',
                        name:'pizza',
                        img:'pizza',
                        menuNum:2,
                        title:'پیتزا',
                    },
                    {
                        id:'sandwich',
                        name:'sandwich',
                        img:'sandwich',
                        menuNum:2,
                        title:'ساندویچ',
                    },
                    {
                        id:'burger',
                        name:'burger',
                        img:'burger',
                        menuNum:2,
                        title:'برگر',
                    },
                    {
                        id:'fried',
                        name:'fried',
                        img:'fried',
                        menuNum:2,
                        title:'سوخاری',
                    },
                    {
                        id:'pasta',
                        name:'pasta',
                        img:'pasta',
                        menuNum:2,
                        title:'پاستا',
                    },
                    {
                        id:'stake',
                        name:'stake',
                        img:'stake',
                        menuNum:2,
                        title:'استیک',
                    },
                ]
            },
            {
                id:'irani',
                name:'irani',
                img:'aush',
                menuNum:1,
                title:'ایرانی',
                subCategory:[
                    {
                        id:'sonati',
                        name:'sonati',
                        img:'aush',
                        menuNum:2,
                        title:'سنتی'
                    }  , 
                    {
                        id:'rice',
                        name:'rice',
                        img:'rice',
                        menuNum:2,
                        title:'پلو ایرانی'
                    }  , 
                    {
                        id:'stew',
                        name:'stew',
                        img:'stew',
                        menuNum:2,
                        title:'خورشت'
                    }  , 
                    {
                        id:'chicken',
                        name:'chicken',
                        img:'chicken',
                        menuNum:2,
                        title:'مرغ'
                    }  , 
                    {
                        id:'gilani',
                        name:'gilani',
                        img:'gilani',
                        menuNum:2,
                        title:'گیلانی'
                    }  , 
                ]
            },
            {
                id:'kebab',
                name:'kebab',
                img:'kebab',
                menuNum:1,
                title:'کباب',
                subCategory:[
                    {
                        id:'beafkebab',
                        name:'beafKebab',
                        img:'kebab',
                        menuNum:2,
                        title:'کباب گوشت',
                    },
                    {
                        id:'chickenkebab',
                        name:'chickenKebab',
                        img:'chickenKebab',
                        menuNum:2,
                        title:'کباب مرغ',
                    },
                ]
            },
            {
                id:'salad',
                name:'salad',
                img:'salad',
                menuNum:1,
                title:'سالاد',
                subCategory:null
            },
            {
                id:'seafood',
                name:'seafood',
                img:'seafood',
                menuNum:1,
                title:'غذای دریایی',
                subCategory:null
            },
            {
                id:'asiafood',
                name:'asiafood',
                img:'asiafood',
                menuNum:1,
                title:'بین المللی',
                subCategory:null
            }
        ]

        ,
        cofe:[
            {
                id:'food',
                name:'food',
                img:'pizza',
                menuNum:1,
                title:'غذا',
                subCategory:[
                { 
                    id:'breakfast',
                    name:'breakfast',
                    img:'breakfast',
                    menuNum:2,
                    title:'صبحانه',
                },
                { 
                    id:'snack',
                    name:'snack',
                    img:'snack',
                    menuNum:2,
                    title:'میان وعده',
                },
                { 
                    id:'cofe-salad',
                    name:'salad',
                    img:'salad',
                    menuNum:2,
                    title:'سالاد',
                },
                { 
                    id:'cofe-sandwich',
                    name:'sandwich',
                    img:'sandwich',
                    menuNum:2,
                    title:'ساندویچ',
                },
                { 
                    id:'cofe-pizza',
                    name:'pizza',
                    img:'pizza',
                    menuNum:2,
                    title:'پیتزا',
                },
                { 
                    id:'cofe-burger',
                    name:'burger',
                    img:'burger',
                    menuNum:2,
                    title:'برگر',
                },
                ]
            },
            {
                id:'warmdrink',
                name:'warmdrink',
                img:'coffe',
                menuNum:1,
                title:'نوشیدنی گرم',
                subCategory:[
                    {
                        id:'coffe',
                        name:'coffe',
                        img:'coffe',
                        menuNum:2,
                        title:'قهوه',
                    },
                    {
                        id:'tea',
                        name:'tea',
                        img:'tea',
                        menuNum:2,
                        title:'چای',
                    },
                ]
            },
            {
                id:'colddrink',
                name:'colddrink',
                img:'colddrink',
                menuNum:1,
                title:'نوشیدنی سرد',
                subCategory:[
                    {
                        id:'juice',
                        name:'juice',
                        img:'juice',
                        menuNum:2,
                        title:'آب میوه',
                    },
                    {
                        id:'milkshake',
                        name:'milkshake',
                        img:'milkshake',
                        menuNum:2,
                        title:'میلک شیک',
                    },
                    {
                        id:'herbal',
                        name:'herbal',
                        img:'herbal',
                        menuNum:2,
                        title:'شربت گیاهی',
                    },
                    {
                        id:'coldcoffe',
                        name:'coldcoffe',
                        img:'coldcoffe',
                        menuNum:2,
                        title:'قهوه سرد',
                    },
                    {
                        id:'glace',
                        name:'glace',
                        img:'glace',
                        menuNum:2,
                        title:'گلاسه',
                    },
                    {
                        id:'icepack',
                        name:'icepack',
                        img:'icepack',
                        menuNum:2,
                        title:'آیس پک',
                    },
                ]
            },
            {
                id:'cake',
                name:'cake',
                img:'cake',
                menuNum:1,
                title:'کیک و دسر',
                subCategory:null
            },
            {
                id:'icecream',
                name:'icecream',
                img:'icecream',
                menuNum:1,
                title:'بستنی',
                subCategory:null
            },
        ]

        ,
        bakery:[
            {
                id:'sangak',
                name:'sangak',
                img:'sangak',
                menuNum:1,
                title:'سنگک',
                subCategory:null
            },
            {
                id:'barbari',
                name:'barbari',
                img:'barbari',
                menuNum:1,
                title:'بربری',
                subCategory:null
            },
            {
                id:'lavash',
                name:'lavash',
                img:'lavash',
                menuNum:1,
                title:'لواش',
                subCategory:null
            },
            {
                id:'taftoon',
                name:'taftoon',
                img:'taftoon',
                menuNum:1,
                title:'تافتون',
                subCategory:null
            },

        ]
        }

